name: Build and Deploy Docker Image

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Release Tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Release triggered with tag: ${{ github.event.release.tag_name }}"
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "Manual trigger with user input tag: ${{ github.event.inputs.release_tag }}"
            echo "RELEASE_TAG=${{ github.event.inputs.release_tag }}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64/v8 \
            -t ${{ secrets.DOCKERHUB_USERNAME  }}/$(basename ${{ github.repository }}):${{ env.RELEASE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME  }}/$(basename ${{ github.repository }}):${{ env.RELEASE_TAG }}
